[[plugins]]
repo = 'tomtom/tcomment_vim'
on_path = '.*'

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
    nnoremap <F5> :GundoToggle<CR>
    let g:gundo_prefer_python3 = 1
'''
on_map = '<F5>'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-q>'
'''
on_map = '<C-q>'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/emmet-vim.vim' '''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/previm.vim' '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_path = '.*'

[[plugins]]
repo = 'cespare/vim-toml'
on_path = '.toml'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_map = '<Space>/'
hook_add = '''
    nnoremap <silent> <Space>/ :OverCommandLine<CR>%s//g<Left><Left>
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
on_map = ':Cheat'
hook_add = '''
    let g:cheatsheet#cheat_file = g:rc_dir . '/cheatsheet.md'
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'mattn/efm-langserver'
on_ft = 'markdown'

[[plugins]]
repo = 'andys8/vim-elm-syntax'
on_path = '.elm'

[[plugins]]
repo='elzr/vim-json'
on_ft = 'json'
hook_add = '''
    let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'evanleck/vim-svelte'
on_path = '.svelte'
hook_add = '''
    let g:svelte_indent_script = 0
    let g:svelte_indent_style = 0
'''

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_path = '.dart'
