[[plugins]]
repo = 'tomtom/tcomment_vim'
on_path = '.*'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/emmet-vim.vim' '''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/previm.vim' '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_path = '.*'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = 'go'
hook_source = '''exec 'source ' . g:rc_dir . '/settings/vim-delve.vim' '''

[[plugins]]
repo = 'jsborjesson/vim-uppercase-sql'
on_ft = 'sql'

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = 'markdown'
