[[plugins]]
repo = 'tomtom/tcomment_vim'
on_path = '.*'

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
    nnoremap <F5> :GundoToggle<CR>
    let g:gundo_prefer_python3 = 1
'''
on_map = '<F5>'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-q>'
'''
on_map = '<C-q>'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/emmet-vim.vim' '''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/previm.vim' '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_path = '.*'

[[plugins]]
repo = 'cespare/vim-toml'
on_path = '.toml'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_map = '<Space>/'
hook_add = '''
    nnoremap <silent> <Space>/ :OverCommandLine<CR>%s//g<Left><Left>
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

