[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/coc-vim.vim' '''

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-expand-region.vim' '''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depend = ['kana/vim-operator-user']
hook_add = '''
    map R  <Plug>(operator-replace)
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-textobj-multiblock.vim' '''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-easymotion.vim' '''

[[plugins]]
repo = 'bling/vim-airline'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-airline.vim' '''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/indentLine.vim' '''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/silicon.vim' '''

[[plugins]]
repo='sheerun/vim-polyglot'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-polyglot.vim' '''

[[plugins]]
repo='voldikss/vim-floaterm'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-floaterm.vim' '''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-gitgutter.vim' '''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-fugitive.vim' '''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merge = 0
rev = 'release'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/fzf.vim' '''

[[plugins]]
repo='vim-skk/denops-skkeleton.vim'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/denops-skkeleton.vim' '''

[[plugins]]
repo='jjo/vim-cue'
