[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/defx.vim' '''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/coc-vim.vim' '''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-expand-region.vim' '''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depend = ['kana/vim-operator-user']
hook_add = '''
    map R  <Plug>(operator-replace)
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-easymotion.vim' '''

[[plugins]]
repo = 'bling/vim-airline'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-airline.vim' '''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/indentLine.vim' '''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-fugitive.vim' '''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-gitgutter.vim' '''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-anzu.vim' '''

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
    autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
hook_add = '''
    omap <silent> ab <Plug>(textobj-multiblock-a)
    omap <silent> ib <Plug>(textobj-multiblock-i)
    xmap <silent> ab <Plug>(textobj-multiblock-a)
    xmap <silent> ib <Plug>(textobj-multiblock-i)
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
bulid = 'bash install.sh'

[[plugins]]
repo = 'tpope/vim-obsession'
