[[plugins]]
repo = 'tomtom/tcomment_vim'
on_path = '.*'

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
    nnoremap <F5> :GundoToggle<CR>
    let g:gundo_prefer_python3 = 1
'''
on_map = '<F5>'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-q>'
'''
on_map = '<C-q>'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/emmet-vim.vim' '''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''exec 'source ' . g:rc_dir . '/settings/previm.vim' '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'sylba2050/auto-pairs'
on_path = '.*'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = ['vue']

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vue']

[[plugins]]
repo = 'cespare/vim-toml'
on_path = '.toml'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_map = '<Space>/'
hook_add = '''
    nnoremap <silent> <Space>/ :OverCommandLine<CR>%s//g<Left><Left>
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
on_map = ':Cheat'
hook_add = '''
    let g:cheatsheet#cheat_file = g:rc_dir . '/cheatsheet.md'
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '/'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-anzu.vim' '''

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_path = '.*'
hook_source = '''
    let g:echodoc#enable_at_startup = 1
    let g:echodoc#type = "floating"
'''

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/vim-go.vim' '''

[[plugins]]
repo = 'mattn/efm-langserver'
on_ft = 'markdown'
