[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    " activate python3
    set pyxversion=3
    " activate deoplete by default
    let g:deoplete#enable_at_startup = 1
'''
hook_post_source = '''
    " delay when displaying completion[msec]
    call deoplete#custom#option('auto_complete_delay', 1)
    " do not distinguish upper or lower when completion
    call deoplete#custom#option('camel_case', 1)
    " number of candidates displayed in the pop-up mene. default 500
    call deoplete#custom#option('max_list', 20)
    " number of characters to be completed
    call deoplete#custom#option('min_pattern_length', 1)
    " selects the first position of the completion candidate
    set completeopt+=noinsert

    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    inoremap <expr><CR> pumvisible() ? deoplete#close_popup() :"\<CR>"
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']
depend = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
depend = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1
depend = ['deoplete.nvim']

[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1
depend = ['deoplete.nvim']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
    let g:user_emmet_mode = 'iv'
    let g:user_emmet_leader_key = '<C-Y>'
    let g:use_emmet_complete_tag = 1
    let g:user_emmet_settings = {
      \ 'lang' : 'ja',
      \ 'html' : {
        \   'filters' : 'html',
        \ },
      \ 'css' : {
        \   'filters' : 'fc',
        \ },
      \ 'php' : {
        \   'extends' : 'html',
        \   'filters' : 'html',
        \ },
      \}
    augroup EmmitVim
      autocmd!
      autocmd FileType * let g:user_emmet_settings.indentation = '               '[:&tabstop]
    augroup END
'''
on_ft = ['html']

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
    nnoremap <F5> :GundoToggle<CR>
    let g:gundo_prefer_python3 = 1
'''
on_map = '<F5>'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-q>'
'''
on_map = '<C-q>'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_path = '.*'
